### PR TITLE
Respond to seppuku too

### PR DESCRIPTION
**Pull request by strugee**
Inspired by @dissolve on IRC.

### CODE REVIEW

**Comment by strugee** [comment]
Fixed the misspelling :thumbsup:

**Comment by strugee** [comment]
Fixed the failing test too but... I really feel like that's not good design. The test is essentially a poor man's smoketest and doesn't actually assert anything useful about the behavior. Plus it's needlessly coupled to implementation.

**Comment by wpears** [comment]
Agreed re: the testing, would gladly accept a PR with expanded test cases 👍

**Comment by strugee** [comment]
@wpears thanks for merging! Don't have the bandwidth right now unfortunately, but filed #2 to track it :/

**Pull request merged**
